set_property SRC_FILE_INFO {cfile:/home/gwrw/Basys3_Master.xdc rfile:../../../../../../Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports XA1_P]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports XA1_N]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name CLKFBIN -source [get_pins mmcm0/MMCME2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks sys_clk_pin] [get_pins mmcm0/MMCME2_BASE_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name mmcm_clk_sig -source [get_pins mmcm0/MMCME2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks sys_clk_pin] [get_pins mmcm0/MMCME2_BASE_inst/CLKOUT1]
