webtalk_init -webtalk_dir /home/gwrw/fir1/fir1.sim/sim_1/behav/xsim/xsim.dir/QuadratureDemodulator_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 26 11:31:06 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "38e3a40b-d7f6-4bb0-9830-3fbf8fee226c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1f4367962a4b4441b8e64d3ba15e400e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 560  @ 2.67GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1450.150 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "17782 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "17.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "153596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 596126181 -regid "" -xml /home/gwrw/fir1/fir1.sim/sim_1/behav/xsim/xsim.dir/QuadratureDemodulator_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/gwrw/fir1/fir1.sim/sim_1/behav/xsim/xsim.dir/QuadratureDemodulator_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/gwrw/fir1/fir1.sim/sim_1/behav/xsim/xsim.dir/QuadratureDemodulator_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
