set_property SRC_FILE_INFO {cfile:/home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_qd/ila_qd/ila_0_in_context.xdc rfile:../../../../../fir1.srcs/sources_1/ip/ila_qd/ila_qd/ila_0_in_context.xdc id:1 order:EARLY scoped_inst:ADCQuadDemodSerial_module/ila0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gwrw/Basys3_Master.xdc rfile:../../../../../../Basys3_Master.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gwrw/fir1/fir1.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins ADCQuadDemodSerial_module/ila0/clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ADCQuadDemodSerial_module/ila0]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK]
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports XA1_P]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports XA1_N]
set_property src_info {type:XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name CLKFBIN -source [get_pins mmcm0/MMCME2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks sys_clk_pin] [get_pins mmcm0/MMCME2_BASE_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name mmcm_clk_sig -source [get_pins mmcm0/MMCME2_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks sys_clk_pin] [get_pins mmcm0/MMCME2_BASE_inst/CLKOUT1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells ADCQuadDemodSerial_module/ila0]
