# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/gwrw/Basys3_Master.xdc

# IP: ip/ila_qd/ila_qd.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_qd || ORIG_REF_NAME==ila_qd} -quiet] -quiet
