# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/gwrw/fir1/fir1.runs/synth_1/TestUARTSPITapBasys3.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gwrw/fir1/fir1.cache/wt [current_project]
set_property parent.project_path /home/gwrw/fir1/fir1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/gwrw/fir1/fir1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  /home/gwrw/fir1/fir1.srcs/sources_1/new/clk_div_generic.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/reg1D.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/Synchronizer.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SimpleMMCM2.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/square_wave_gen.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/MAFilter1Bit.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/EdgeDetectorFSM.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/EdgeDetector.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/ParEdgeDetector.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SPITapFSM.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/Timer.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SPITap.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SerialTxFSM.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SerialTx.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/UARTSPITap.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/TestUARTSPITapBasys3.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/PushButtonToggle.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SPITransactionFSM.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SPITransaction.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SerialRxFSM.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SerialRx.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/UARTSPIBridge.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/TestUARTSPIBridgeBasys3.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SimpleMMCM.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/ADC1Bit.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/reg2D.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/pdm_generic.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/fun_gen_sr.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/shift_mult_generic.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/DAC_ADC.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/MAFilter.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/SequentialAdder.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/decoder.vhdl
  /home/gwrw/fir1/fir1.srcs/sources_1/new/diff_accum.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/diff_out_test.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/encoder.vhdl
  /home/gwrw/fir1/fir1.srcs/sources_1/new/fun_gen.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/mult_generic.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/pulsing_leds.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/reg_add_generic.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/reg_mult_generic.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/register.vhdl
  /home/gwrw/fir1/fir1.srcs/sources_1/new/shorten.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/sin_wave_gen.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/test_values.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/test_fun_gen.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/test_synth.vhdl
  /home/gwrw/fir1/fir1.srcs/sources_1/new/mult_generic_tb.vhd
  /home/gwrw/fir1/fir1.srcs/sources_1/new/PulseGenerator.vhd
}
read_ip -quiet /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_spitransaction/ila_spitransaction.xci
set_property used_in_synthesis false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_spitransaction/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_spitransaction/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_spitransaction/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_spitransaction/ila_spitransaction_ooc.xdc]

read_ip -quiet /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspi_testing/ila_uartspi_testing.xci
set_property used_in_synthesis false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspi_testing/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspi_testing/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspi_testing/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspi_testing/ila_uartspi_testing_ooc.xdc]

read_ip -quiet /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_uartspitaptesting.xci
set_property used_in_synthesis false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_uartspitaptesting_ooc.xdc]

read_ip -quiet /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitap/ila_uartspitap.xci
set_property used_in_synthesis false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitap/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitap/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitap/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitap/ila_uartspitap_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/gwrw/Basys3_Master.xdc
set_property used_in_implementation false [get_files /home/gwrw/Basys3_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top TestUARTSPITapBasys3 -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TestUARTSPITapBasys3.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TestUARTSPITapBasys3_utilization_synth.rpt -pb TestUARTSPITapBasys3_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
