# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_uartspitaptesting.xci
# IP: The module: 'ila_uartspitaptesting' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uartspitaptesting'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uartspitaptesting'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_uartspitaptesting_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uartspitaptesting'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_uartspitaptesting.xci
# IP: The module: 'ila_uartspitaptesting' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uartspitaptesting'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uartspitaptesting'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/gwrw/fir1/fir1.srcs/sources_1/ip/ila_uartspitaptesting/ila_uartspitaptesting_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uartspitaptesting'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
